services:
  db:
    image: postgres:16-alpine
    container_name: fabricsync_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: Taki2399
      POSTGRES_DB: fabricsync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build:
      context: ./backend      # Points to your backend folder
      dockerfile: Dockerfile  # Looks for the Dockerfile inside it
      network: host           # Bypasses the Windows network bottleneck
    ports:
      - "3000:3000"           # Exposes your API port to your local browser
    env_file:
      - ./backend/.env
    depends_on:
      - db

volumes:
  postgres_data:
